apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      # passar todos os valores
      envFrom:
        - configMapRef:
            name: db-configmap

      # se eu quiser passar um valor único
      # env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_ROOT_PASSWORD