apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
    # está sendo acessado de forma externa, então tem que ser uma porta única, não podemos utilizar a 30000, já está sendo utilizada no portal-noticias
      nodePort: 30001
  selector:
    app: sistema-noticias