apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
      # qual porta que ele vai ouvir
    - port: 9000
      # qual a porta que ele vai despachar o serviço
      # quando defino que a porta que eu escuto é diferente, ou seja porta 9000, ele faz um bind
      # ou seja, ele pega o tráfego da 9000 e passa pro IP do container na porta 80 que é de fato
      # onde está o conteúdo
      targetPort: 80